# docker-compose.yml fayli
version: "3.9"

services:
  bot:
    build: .
    container_name: coffe_bot
    restart: always
    env_file: 
      - .env
    volumes:
      - .:/app
    command: python3 bot.py